version: '3.3'
services:
  infoapp:
    container_name:  infoapp
    restart: always
    build: .
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - "MONGO_DB_CONNECTION_URL=mongodb://mongo:27017"
      - "Port= 8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - /data/db
    ports:
      - 27017:27017
